### ISSUE TITLE
Literaturstudie: Gamification

### ISSUE THREAD

**Issue by laughing7y** [laughing7y/magicMashRoom#1]

**Comment by laughing7y** [comment]
Hab den Titel geändert, um die Abarbeitung etwas granularer zu gestalten. Sieht besser aus und kann bei aufkommenden Problemen besser gelöst werden.

**Comment by mrente33** [comment]
[Gamification of Education.pdf](https://github.com/laughing7y/magicMashRoom/files/1457162/Gamification.of.Education.pdf)

**Comment by mrente33** [comment]
[GamificationinEducation.pdf](https://github.com/laughing7y/magicMashRoom/files/1457166/GamificationinEducation.pdf)
