### ISSUE TITLE
Literaturstudie: Serious Gaming

### ISSUE THREAD

**Issue by laughing7y** [laughing7y/magicMashRoom#8]
Siehe ersten Kommentar bei #1 

Diese Studie bezieht sich mehr auf die Aspekte "Lerneffekte", "Überbringen von Inhalten über spiel. Kontext" o.ä.

**Comment by mrente33** [comment]
[Our Princess Is in Another Castle- A Review of Trends in Serious Gaming for Education.pdf](https://github.com/laughing7y/magicMashRoom/files/1457146/Our.Princess.Is.in.Another.Castle-.A.Review.of.Trends.in.Serious.Gaming.for.Education.pdf)
